# Generated by Django 4.2.6 on 2023-11-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_admin_remove_attendancereport_attendance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
