# Generated by Django 4.2.6 on 2023-11-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_staffslogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150)),
                ('course_description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coursecategory')),
                ('cpourse_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coursetype')),
            ],
        ),
        migrations.DeleteModel(
            name='StaffsLogin',
        ),
    ]
