# Generated by Django 4.2.6 on 2023-11-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_coursecreation_delete_staffslogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='coursecategory',
            old_name='course_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='coursecreation',
            old_name='course_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='coursecreation',
            old_name='cpourse_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='coursetype',
            old_name='course_description',
            new_name='description',
        ),
    ]
