# Generated by Django 4.2.6 on 2023-11-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
