# Generated by Django 4.2.6 on 2023-11-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_delete_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_grade', models.CharField(max_length=2)),
                ('lower_bound', models.DecimalField(decimal_places=2, max_digits=5)),
                ('upper_bound', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='pass_fail_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
