# Generated by Django 4.2.6 on 2023-11-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_grade_enrollment_pass_fail_status_enrollment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrolledStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('grade', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='pass_fail_status',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='score',
        ),
    ]
