# Generated by Django 4.2.6 on 2023-11-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_enrolledstudent_delete_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledstudent',
            name='grade',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('A+', 'Excellent'), ('A', 'Very Good'), ('B+', 'Good'), ('B', 'Above Average'), ('C+', 'Average'), ('C', 'Below Average'), ('D', 'Poor'), ('E', 'Fail')], max_length=5, null=True),
        ),
    ]
