# Generated by Django 4.2.6 on 2023-11-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_enrolledstudent_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledstudent',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
