# Generated by Django 4.2.6 on 2023-11-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_enrolledstudent_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledstudent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='enrolledstudent',
            name='full_name',
        ),
    ]
