# Generated by Django 4.2.6 on 2023-11-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_enrolledstudent_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnrolledStudent',
        ),
    ]
