# Generated by Django 4.2.6 on 2023-11-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_grade_evaluation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='grade',
            name='pass_fail',
            field=models.CharField(max_length=4),
        ),
    ]
