# Generated by Django 4.2.6 on 2023-11-11 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_staffprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='community',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='religion',
        ),
    ]
