# Generated by Django 4.2.6 on 2023-11-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_staffprofile_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staffCode',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
