# Generated by Django 4.2.6 on 2023-11-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.enrollment'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], default=1, max_length=1),
        ),
    ]
