# Generated by Django 4.2.6 on 2023-11-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_attendance_student_attendance_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('OD', 'OnDuty')], default='1', max_length=2),
        ),
    ]
