# Generated by Django 4.2.6 on 2023-11-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_attendance_end_time_attendance_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='mobile_no',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='staffs',
            name='otp_digit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='verify_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='otp_digit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='verify_status',
            field=models.BooleanField(default=False),
        ),
    ]
