# Generated by Django 4.2.6 on 2023-11-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_studentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='bloodGroup',
            field=models.CharField(choices=[('A+', 'A+'), ('AB+', 'AB+'), ('O+', 'O+'), ('B+', 'B+'), ('A-', 'A-'), ('AB-', 'AB-'), ('O-', 'O-'), ('B-', 'B-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='community',
            field=models.CharField(choices=[('BC', 'BC'), ('MBC', 'MBC'), ('OBC', 'OBC'), ('ST', 'ST'), ('SC', 'SC'), ('General Class', 'General Class')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='emergencyMobileNumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='maritalStatus',
            field=models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mobileNumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='religion',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian')], max_length=20),
        ),
    ]
