# Generated by Django 4.2.6 on 2023-11-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_studentprofile_bloodgroup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='otp_digit',
        ),
        migrations.RemoveField(
            model_name='student',
            name='verify_status',
        ),
    ]
