# Generated by Django 4.2.6 on 2023-11-14 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_studentprofile_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student',
        ),
    ]
