# Generated by Django 4.2.6 on 2023-11-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_studentprofile_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
