# Generated by Django 4.2.6 on 2023-11-15 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
