# Generated by Django 4.2.6 on 2023-11-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
