# Generated by Django 4.2.6 on 2023-11-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
