# Generated by Django 4.2.6 on 2023-11-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_applicant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
