# Generated by Django 4.2.6 on 2023-11-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_of_join',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='register_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='student_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
