# Generated by Django 4.2.6 on 2023-11-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_document_date_of_join_document_department_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
