# Generated by Django 4.2.6 on 2023-11-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('student_name', models.CharField(max_length=255)),
                ('register_number', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=50)),
                ('date_of_join', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
