# Generated by Django 4.2.6 on 2023-11-17 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_document_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='staffs',
        ),
    ]
