# Generated by Django 4.2.6 on 2023-11-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_remove_staffprofile_staffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='staffid',
            field=models.CharField(blank=True, default=1, max_length=100, null=True),
        ),
    ]
