# Generated by Django 4.2.6 on 2023-11-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_staffprofile_staffid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='staffid',
        ),
    ]
