# Generated by Django 4.2.6 on 2023-11-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_staffprofile_staffid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='staffid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
