# Generated by Django 4.2.6 on 2023-11-19 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_staffprofile_staffid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffProfile',
        ),
    ]
