# Generated by Django 4.2.6 on 2023-11-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_delete_staffprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='otp_digit',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='verify_status',
        ),
        migrations.AddField(
            model_name='staffs',
            name='bloodGroup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='dateOfJoining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='emergencyMobileNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='firstName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='lastName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='maritalStatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='mobileNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='staffs',
            name='staffCode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='staffRoll',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='staffType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
