# Generated by Django 4.2.6 on 2023-11-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_remove_staffs_mobile_no_remove_staffs_otp_digit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='mobile_no',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
