# Generated by Django 4.2.6 on 2023-11-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_alter_student_full_name_alter_student_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
