# Generated by Django 4.2.6 on 2023-11-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_staffstudentchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffstudentchat',
            name='msg_text',
            field=models.TextField(max_length=100),
        ),
    ]
