# Generated by Django 4.2.6 on 2023-11-30 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_course_created_by_alter_enrollment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.staffs'),
        ),
    ]
