# Generated by Django 4.2.6 on 2023-11-30 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_enrollment_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='staff',
            new_name='subject_staff',
        ),
    ]
