# Generated by Django 4.2.6 on 2023-12-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_rename_staff_enrollment_subject_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
