# Generated by Django 4.2.6 on 2023-12-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_student_admission_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission_status',
        ),
    ]
