# Generated by Django 4.2.6 on 2023-12-01 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_student_admission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='customuser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customuser'),
        ),
    ]
