# Generated by Django 4.2.6 on 2023-12-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_student_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='customuser',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
