# Generated by Django 4.2.6 on 2023-12-01 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
