# Generated by Django 4.2.6 on 2023-12-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_applicant_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='student',
        ),
    ]
