# Generated by Django 4.2.6 on 2023-12-01 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_alter_enrollment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('OD', 'OnDuty')], max_length=2),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enrollment'),
        ),
    ]
