# Generated by Django 4.2.6 on 2023-12-09 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_remove_student_user_staffstudentchat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffstudentchat',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.staffs'),
        ),
        migrations.AlterField(
            model_name='staffstudentchat',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
