# Generated by Django 4.2.6 on 2023-12-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_fees_student_alter_payment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='otp_digit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='staffs',
            name='verify_status',
            field=models.BooleanField(default=True),
        ),
    ]
