# Generated by Django 4.2.6 on 2023-12-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_staffs_otp_digit_staffs_verify_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffs',
            name='verify_status',
            field=models.BooleanField(default=False),
        ),
    ]
