# Generated by Django 4.2.6 on 2023-12-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_student_otp_digit_student_verify_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='login_via_otp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='login_via_otp',
            field=models.BooleanField(default=False),
        ),
    ]
