# Generated by Django 4.2.6 on 2023-12-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_staffs_login_via_otp_student_login_via_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
