# Generated by Django 4.2.6 on 2023-12-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_document_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='date_of_join',
        ),
        migrations.RemoveField(
            model_name='document',
            name='department',
        ),
        migrations.RemoveField(
            model_name='document',
            name='register_number',
        ),
        migrations.RemoveField(
            model_name='document',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='year',
        ),
    ]
