# Generated by Django 4.2.6 on 2023-12-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_course_acadamic_year_course_course_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='acadamic_year',
            field=models.CharField(blank=True, help_text='Format: YYYY-YYYY', max_length=9, null=True, unique=True),
        ),
    ]
