# Generated by Django 4.2.6 on 2024-01-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_alter_course_acadamic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='emailid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
