# Generated by Django 4.2.6 on 2024-01-01 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0114_staffs_emailid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='emailid',
        ),
    ]
