# Generated by Django 4.2.6 on 2024-01-04 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_remove_staffs_emailid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='acadamic_year',
            new_name='academic_year',
        ),
    ]
