# Generated by Django 4.2.6 on 2024-01-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_student_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='regulation',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
