# Generated by Django 4.2.6 on 2024-01-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_remove_student_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='period',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
