# Generated by Django 4.2.6 on 2024-01-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_attendance_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade_academic_year',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
