# Generated by Django 4.2.6 on 2024-01-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_grade_grade_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_academic_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
