# Generated by Django 4.2.6 on 2024-01-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_alter_grade_grade_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_academic_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
