# Generated by Django 4.2.6 on 2024-01-31 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_attendance_attendance_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applicant_academic_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
