# Generated by Django 4.2.6 on 2024-02-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_remove_student_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='full_name',
        ),
    ]
