# Generated by Django 4.2.6 on 2024-02-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_remove_staffs_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
