# Generated by Django 4.2.6 on 2024-02-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0130_staffs_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
