# Generated by Django 4.2.6 on 2024-02-03 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_student_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
