# Generated by Django 4.2.6 on 2024-02-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0135_alter_course_regulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='regulation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
