# Generated by Django 4.2.6 on 2024-02-14 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_flatpage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlatPage',
        ),
    ]
