# Generated by Django 4.2.6 on 2024-02-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0142_conatct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conatct',
            new_name='Contact',
        ),
    ]
