# Generated by Django 4.2.6 on 2024-02-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0143_rename_conatct_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='confirm_password',
        ),
    ]
