# Generated by Django 4.2.6 on 2024-02-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0144_remove_student_confirm_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
