# Generated by Django 4.2.6 on 2024-02-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0149_staffs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='user',
        ),
    ]
